# This is a basic workflow to help you get started with Actions

name: Generating Debug build

# Controls when the action will run. 
on:
  push:
    branches: [ master ]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: '11'


#      - name: Build Debug APK
#        run: bash ./gradlew assembleDebug --stacktrace
#(or)
      -name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle- Generate Apk
        run: ./gradlew build

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
            name: debug.apk
            path: app/build/outputs/apk/debug/app-debug.apk
